import * as LucideIcons from 'lucide-react'

// Extract specific icons
const {
  Video,
  Home,
  Settings,
  Film,
  Library,
  Calendar,
  BarChart3,
  Plus,
  Play,
  Pause,
  Download,
  Trash2,
  Edit,
  Eye,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Zap,
  Sparkles,
  Mic,
  Image,
  Type,
  Music,
  Layers,
  MoreVertical,
  ChevronRight,
  ChevronDown,
  Search,
  Bell,
  User,
  LogOut,
  Menu,
  X,
  Upload,
  Copy,
  RefreshCw,
  Moon,
  Sun,
  CreditCard,
  Key,
  Shield,
  Users,
  Server,
  Database,
  HardDrive,
  Activity,
  Globe,
  Code,
  FileText,
  Terminal,
  Box,
  Container,
  Cloud,
  Link,
  ExternalLink,
  Instagram,
  Twitter,
  Youtube,
  Send,
  MessageSquare,
  Star,
  Heart,
  ThumbsUp,
  Share2,
  MoreHorizontal,
  Filter,
  SortAsc,
  Grid,
  List,
  Maximize2,
  Minimize2,
  Volume2,
  VolumeX,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  PlayCircle,
  PauseCircle,
  Square,
  Circle,
  Trash,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FolderPlus,
  Edit2,
  EyeOff,
  Loader2,
  Loader,
  TrendingUp,
} = LucideIcons

export const Icons = {
  video: Video,
  home: Home,
  settings: Settings,
  film: Film,
  library: Library,
  calendar: Calendar,
  chart: BarChart3,
  plus: Plus,
  play: Play,
  pause: Pause,
  download: Download,
  trash: Trash,
  edit: Edit,
  eye: Eye,
  clock: Clock,
  check: CheckCircle,
  x: XCircle,
  alert: AlertCircle,
  zap: Zap,
  sparkles: Sparkles,
  mic: Mic,
  image: Image,
  type: Type,
  music: Music,
  layers: Layers,
  more: MoreVertical,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  search: Search,
  bell: Bell,
  user: User,
  logout: LogOut,
  menu: Menu,
  xClose: X,
  upload: Upload,
  copy: Copy,
  refresh: RefreshCw,
  moon: Moon,
  sun: Sun,
  credit: CreditCard,
  key: Key,
  shield: Shield,
  users: Users,
  server: Server,
  database: Database,
  storage: HardDrive,
  activity: Activity,
  globe: Globe,
  code: Code,
  file: FileText,
  terminal: Terminal,
  box: Box,
  container: Container,
  cloud: Cloud,
  link: Link,
  external: ExternalLink,
  instagram: Instagram,
  twitter: Twitter,
  youtube: Youtube,
  send: Send,
  message: MessageSquare,
  star: Star,
  heart: Heart,
  like: ThumbsUp,
  share: Share2,
  moreHorizontal: MoreHorizontal,
  filter: Filter,
  sort: SortAsc,
  grid: Grid,
  list: List,
  maximize: Maximize2,
  minimize: Minimize2,
  volume: Volume2,
  volumeOff: VolumeX,
  skipBack: SkipBack,
  skipForward: SkipForward,
  rewind: Rewind,
  fastForward: FastForward,
  repeat: Repeat,
  shuffle: Shuffle,
  playCircle: PlayCircle,
  pauseCircle: PauseCircle,
  square: Square,
  circle: Circle,
  folder: Folder,
  folderOpen: FolderOpen,
  filePlus: FilePlus,
  folderPlus: FolderPlus,
  editAlt: Edit2,
  eyeOff: EyeOff,
  spinner: Loader2,
  loader: Loader,
  trendingUp: TrendingUp,
}
